# Generated by Django 4.2.20 on 2025-10-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_alter_about_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to='team_images/'),
        ),
    ]
