# Generated by Django 4.2.20 on 2025-10-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0003_alter_about_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_skill', models.CharField(max_length=200)),
                ('input_resume', models.ImageField(upload_to='')),
            ],
        ),
    ]
