# Generated by Django 4.2.20 on 2025-10-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_alter_resume_form_input_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_form',
            name='input_skill',
            field=models.TextField(),
        ),
    ]
