# Generated by Django 4.2.20 on 2025-10-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_alter_resume_form_input_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_form',
            name='input_skill',
            field=models.CharField(max_length=200),
        ),
    ]
