# Generated by Django 4.2.20 on 2025-10-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0008_about_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=20)),
                ('question', models.TextField(max_length=30)),
            ],
        ),
    ]
