# Generated by Django 4.2.20 on 2025-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0013_rename_qa_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
