# Generated by Django 4.2.20 on 2025-10-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_resume_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_form',
            name='input_resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume_form',
            name='input_skill',
            field=models.CharField(max_length=500),
        ),
    ]
