# Generated by Django 4.2.20 on 2025-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0007_alter_resume_form_input_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
