# Generated by Django 4.2.20 on 2025-10-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0011_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=20)),
                ('question1', models.TextField(max_length=1000)),
                ('question2', models.TextField(max_length=1000)),
                ('question3', models.TextField(max_length=1000)),
                ('question4', models.TextField(max_length=1000)),
                ('question5', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
