# Generated by Django 4.2.20 on 2025-10-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0012_qa_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QA',
            new_name='Ques',
        ),
    ]
