# Generated by Django 4.2.20 on 2026-01-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0014_alter_about_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('DevOps Engineer', 'DevOps Engineer'), ('Web Developer', 'Web Developer'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Cybersecurity Analyst', 'Cybersecurity Analyst'), ('Project Manager', 'Project Manager'), ('Cloud Engineer', 'Cloud Engineer'), ('Blockchain Developer', 'Blockchain Developer'), ('Software Engineer', 'Software Engineer'), ('Data Analyst', 'Data Analyst'), ('Database Administrator', 'Database Administrator'), ('Data Scientist', 'Data Scientist'), ('AI Engineer', 'AI Engineer'), ('Big Data Engineer', 'Big Data Engineer'), ('Business Analyst', 'Business Analyst'), ('Mobile App Developer', 'Mobile App Developer')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='About.jobrole')),
            ],
        ),
    ]
